# Generated by Django 4.2.14 on 2025-04-27 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appointments", "0003_initial"),
        ("therapist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapistprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="therapist_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sessionnote",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_note",
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="sessionnote",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "patient"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_session_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sessionnote",
            name="therapist",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "therapist"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="therapist_session_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clientfeedback",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="clientfeedback",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "patient"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_feedback_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clientfeedback",
            name="therapist",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "therapist"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="therapist_feedback_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="sessionnote",
            index=models.Index(
                fields=["-session_date"], name="therapist_s_session_22a96f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionnote",
            index=models.Index(
                fields=["therapist", "patient"], name="therapist_s_therapi_cac6e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientfeedback",
            index=models.Index(
                fields=["-timestamp"], name="therapist_c_timesta_20cee1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientfeedback",
            index=models.Index(
                fields=["therapist", "rating"], name="therapist_c_therapi_ba58ba_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="clientfeedback",
            constraint=models.UniqueConstraint(
                fields=("patient", "therapist", "appointment"),
                name="unique_appointment_feedback",
            ),
        ),
    ]
