# Generated by Django 4.2.7 on 2025-04-27 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("therapist", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapistprofile",
            name="license_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="therapistprofile",
            name="years_of_experience",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
