# Generated by Django 4.2.7 on 2025-04-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("therapist", "0003_alter_therapistprofile_license_expiry_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="therapistprofile",
            options={"ordering": ["user__username"]},
        ),
        migrations.AddIndex(
            model_name="therapistprofile",
            index=models.Index(fields=["user"], name="therapist_t_user_id_6b9d21_idx"),
        ),
        migrations.AddIndex(
            model_name="therapistprofile",
            index=models.Index(
                fields=["is_verified", "verification_status"],
                name="therapist_t_is_veri_be77c1_idx",
            ),
        ),
    ]
