# Generated by Django 4.2.7 on 2025-04-27 20:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("therapist", "0004_alter_therapistprofile_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="therapistprofile",
            name="accepts_insurance",
        ),
        migrations.RemoveField(
            model_name="therapistprofile",
            name="education",
        ),
        migrations.RemoveField(
            model_name="therapistprofile",
            name="hourly_rate",
        ),
        migrations.RemoveField(
            model_name="therapistprofile",
            name="insurance_providers",
        ),
        migrations.RemoveField(
            model_name="therapistprofile",
            name="session_duration",
        ),
    ]
