# Generated by Django 4.2.7 on 2025-04-27 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("therapist", "0005_remove_therapistprofile_accepts_insurance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapistprofile",
            name="accepts_insurance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="education",
            field=models.JSONField(
                default=list, help_text="List of educational qualifications"
            ),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="insurance_providers",
            field=models.JSONField(
                default=list, help_text="List of accepted insurance providers"
            ),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="session_duration",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Default session duration in minutes",
                validators=[
                    django.core.validators.MinValueValidator(15),
                    django.core.validators.MaxValueValidator(180),
                ],
            ),
        ),
    ]
