# Generated by Django 4.2.7 on 2025-04-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("therapist", "0006_therapistprofile_accepts_insurance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapistprofile",
            name="video_session_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
