# Generated by Django 4.2.7 on 2025-04-28 11:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("therapist", "0007_therapistprofile_video_session_link"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClientFeedback",
        ),
    ]
