# Generated by Django 4.2.14 on 2025-04-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_edited", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PollOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_text", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PollVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("video", "Video"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "topics",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mental_health", "Mental Health"),
                            ("therapy", "Therapy"),
                            ("self_care", "Self Care"),
                            ("mindfulness", "Mindfulness"),
                            ("stress_management", "Stress Management"),
                            ("relationships", "Relationships"),
                            ("personal_growth", "Personal Growth"),
                            ("anxiety", "Anxiety"),
                            ("depression", "Depression"),
                            ("wellness", "Wellness"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(default="public", editable=False, max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("link_url", models.URLField(blank=True, null=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                (
                    "tags",
                    models.CharField(
                        choices=[
                            ("mental_health", "Mental Health"),
                            ("therapy", "Therapy"),
                            ("self_care", "Self Care"),
                            ("mindfulness", "Mindfulness"),
                            ("stress_management", "Stress Management"),
                            ("relationships", "Relationships"),
                            ("personal_growth", "Personal Growth"),
                            ("anxiety", "Anxiety"),
                            ("depression", "Depression"),
                            ("wellness", "Wellness"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("like", "Like 👍"),
                            ("love", "Love ❤️"),
                            ("support", "Support 🤝"),
                            ("insightful", "Insightful 💡"),
                            ("celebrate", "Celebrate 🎉"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(default="#3498DB", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
