# Generated by Django 4.2.7 on 2025-04-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "-created_at"], name="notificatio_user_id_05b4bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "read"], name="notificatio_user_id_878a13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type", "-created_at"],
                name="notificatio_notific_c4ec61_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationtype",
            index=models.Index(
                fields=["default_enabled"], name="notificatio_default_43761e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationtype",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_8e213d_idx"
            ),
        ),
    ]
