version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      ALLOWED_HOSTS: "*"  # Allow all hosts or specify your host IP
    command: python manage.py runserver 0.0.0.0:8000