# Generated by Django 4.2.14 on 2025-04-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("appointments", "0002_initial"),
        ("therapist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="therapist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments_as_therapist",
                to="therapist.therapistprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["therapist", "appointment_date"],
                name="appointment_therapi_3555d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "appointment_date"],
                name="appointment_patient_8037cd_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                check=models.Q(("appointment_date__gt", models.F("created_at"))),
                name="appointment_date_future_check",
            ),
        ),
    ]
