# Generated by Django 4.2.7 on 2025-04-27 19:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0002_initial"),
        ("therapist", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appointments", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitingListEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_date", models.DateField()),
                (
                    "preferred_time_slots",
                    models.JSONField(
                        help_text="List of preferred time slots in HH:MM format"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("notified", "Notified"),
                            ("booked", "Booked"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["requested_date", "created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["-appointment_date"]},
        ),
        migrations.RemoveConstraint(
            model_name="appointment",
            name="appointment_date_future_check",
        ),
        migrations.AddField(
            model_name="appointment",
            name="ai_recommendations",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="AI-generated recommendations for the therapy session",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="last_rescheduled",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="original_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reschedule_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="appointment",
            name="rescheduled_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rescheduled_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="video_session_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_id",
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="patient.patientprofile",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("confirmed", "Confirmed"),
                    ("rescheduled", "Rescheduled"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("missed", "Missed"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="therapist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="therapist.therapistprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_date"], name="appointment_appoint_5be6a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status"], name="appointment_status_8fe9d7_idx"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "status"], name="appointment_patient_44acdc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["therapist", "status"], name="appointment_therapi_e09ec9_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="appointment",
            table=None,
        ),
        migrations.AddField(
            model_name="waitinglistentry",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waiting_list_entries",
                to="patient.patientprofile",
            ),
        ),
        migrations.AddField(
            model_name="waitinglistentry",
            name="therapist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waiting_list_entries",
                to="therapist.therapistprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="waitinglistentry",
            index=models.Index(
                fields=["requested_date"], name="appointment_request_3b0228_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waitinglistentry",
            index=models.Index(fields=["status"], name="appointment_status_e61455_idx"),
        ),
        migrations.AddIndex(
            model_name="waitinglistentry",
            index=models.Index(
                fields=["therapist", "status"], name="appointment_therapi_3ab338_idx"
            ),
        ),
    ]
