# Generated by Django 4.2.7 on 2025-04-28 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appointments", "0004_waitinglistentry_alter_appointment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="rescheduled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rescheduled_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
