# Generated by Django 4.2.7 on 2025-04-28 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0005_alter_appointment_rescheduled_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="pain_level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Patient's pain level (0-10) reported during appointment",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
