# Generated by Django 4.2.14 on 2025-04-27 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("very_negative", "Very Negative"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                            ("positive", "Positive"),
                            ("very_positive", "Very Positive"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_private", models.BooleanField(default=True)),
                ("shared_with_therapist", models.BooleanField(default=False)),
                (
                    "weather",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sunny", "Sunny"),
                            ("cloudy", "Cloudy"),
                            ("rainy", "Rainy"),
                            ("stormy", "Stormy"),
                            ("snowy", "Snowy"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "activities",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exercise", "Exercise"),
                            ("reading", "Reading"),
                            ("meditation", "Meditation"),
                            ("socializing", "Socializing"),
                            ("working", "Working"),
                            ("cooking", "Cooking"),
                            ("gardening", "Gardening"),
                            ("dancing", "Dancing"),
                            ("gaming", "Gaming"),
                            ("traveling", "Traveling"),
                            ("shopping", "Shopping"),
                            ("listening_to_music", "Listening to Music"),
                            ("watching_tv", "Watching TV"),
                            ("yoga", "Yoga"),
                            ("walking", "Walking"),
                            ("running", "Running"),
                            ("painting", "Painting"),
                            ("writing", "Writing"),
                            ("cleaning", "Cleaning"),
                            ("photography", "Photography"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Journal Entries",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
