# Generated by Django 4.2.14 on 2025-04-27 13:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoodLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mood_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "energy_level",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Very Low"),
                            (2, "Low"),
                            (3, "Moderate"),
                            (4, "High"),
                            (5, "Very High"),
                        ],
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "activities",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Exercise", "Exercise"),
                            ("Meditation", "Meditation"),
                            ("Reading", "Reading"),
                            ("Socializing", "Socializing"),
                            ("Cooking", "Cooking"),
                            ("Working", "Working"),
                            ("Sleeping", "Sleeping"),
                            ("Walking", "Walking"),
                            ("Running", "Running"),
                            ("Yoga", "Yoga"),
                            ("Dancing", "Dancing"),
                            ("Gaming", "Gaming"),
                            ("Traveling", "Traveling"),
                            ("Shopping", "Shopping"),
                            ("Listening to Music", "Listening to Music"),
                            ("Watching TV", "Watching TV"),
                            ("Gardening", "Gardening"),
                            ("Art", "Art"),
                            ("Writing", "Writing"),
                            ("Cleaning", "Cleaning"),
                        ],
                        help_text="Select one activity from a fixed list",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("logged_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "journal_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mood_log",
                        to="journal.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-logged_at"],
            },
        ),
    ]
