# Generated by Django 4.2.14 on 2025-04-27 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mood", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moodlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mood_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="moodlog",
            index=models.Index(
                fields=["user", "logged_at"], name="mood_moodlo_user_id_1afc91_idx"
            ),
        ),
    ]
