# Generated by Django 4.2.7 on 2025-05-01 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotconversation",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users participating in the conversation",
                related_name="participated_chatbot_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="chatbotconversation",
            name="user",
            field=models.ForeignKey(
                help_text="The user who owns this conversation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_chatbot_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
