# Generated by Django 4.2.7 on 2025-05-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0002_chatbotconversation_participants_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbotconversation",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional metadata for the conversation",
            ),
        ),
    ]
