# Generated by Django 4.2.7 on 2025-05-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0003_alter_chatbotconversation_metadata"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["conversation", "timestamp"],
                name="chatbot_cha_convers_a85429_idx",
            ),
        ),
    ]
