# Generated by Django 4.2.7 on 2025-04-27 22:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientprofile",
            name="current_medications",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="medical_history",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="pain_level",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="treatment_plan",
        ),
    ]
