# Generated by Django 4.2.7 on 2025-04-28 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0003_remove_patientprofile_current_medications_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientprofile",
            name="last_appointment",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="next_appointment",
        ),
    ]
