# Generated by Django 4.2.7 on 2025-04-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0004_remove_patientprofile_last_appointment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="last_appointment",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="next_appointment",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
