# Generated by Django 4.2.7 on 2025-04-28 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0006_create_client_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientprofile",
            name="last_appointment",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="next_appointment",
        ),
    ]
