// Mock data for the application

// Mock upcoming appointments for patient
export const mockUpcomingAppointments = [
    {
      id: "apt-001",
      therapistName: "Dr. Sarah Johnson",
      therapistSpecialty: "Cognitive Behavioral Therapy",
      date: new Date(2025, 4, 15),
      time: "10:00 AM",
      duration: 60,
      status: "confirmed",
      notes: "Follow-up session on anxiety management techniques",
      videoLink: "https://meet.example.com/dr-johnson-room",
    },
    {
      id: "apt-002",
      therapistName: "Dr. Michael Chen",
      therapistSpecialty: "Family Therapy",
      date: new Date(2025, 4, 20),
      time: "2:00 PM",
      duration: 90,
      status: "scheduled",
      notes: "Initial consultation",
    },
  ]
  
  // Mock past appointments for patient
  export const mockPastAppointments = [
    {
      id: "apt-003",
      therapistName: "Dr. Sarah Johnson",
      therapistSpecialty: "Cognitive Behavioral Therapy",
      date: new Date(2025, 3, 10),
      time: "11:00 AM",
      duration: 60,
      status: "completed",
      notes: "Initial assessment",
    },
    {
      id: "apt-004",
      therapistName: "Dr. Sarah Johnson",
      therapistSpecialty: "Cognitive Behavioral Therapy",
      date: new Date(2025, 3, 25),
      time: "10:00 AM",
      duration: 60,
      status: "missed",
      notes: "Follow-up session",
    },
    {
      id: "apt-005",
      therapistName: "Dr. Robert Williams",
      therapistSpecialty: "Psychotherapy",
      date: new Date(2025, 2, 15),
      time: "3:00 PM",
      duration: 60,
      status: "cancelled",
      notes: "Cancelled due to illness",
    },
  ]
  
  // Mock therapist appointments
  export const mockTherapistAppointments = [
    {
      id: "apt-101",
      patientName: "John Smith",
      date: new Date(2025, 4, 6),
      time: "9:00 AM",
      duration: 60,
      status: "confirmed",
      notes: "Weekly session",
      videoLink: "https://meet.example.com/session-101",
    },
    {
      id: "apt-102",
      patientName: "Emily Johnson",
      date: new Date(2025, 4, 6),
      time: "11:00 AM",
      duration: 60,
      status: "confirmed",
      notes: "Follow-up on anxiety management",
      videoLink: "https://meet.example.com/session-102",
    },
    {
      id: "apt-103",
      patientName: "Michael Brown",
      date: new Date(2025, 4, 6),
      time: "2:00 PM",
      duration: 90,
      status: "confirmed",
      notes: "Family therapy session",
      videoLink: "https://meet.example.com/session-103",
    },
    {
      id: "apt-104",
      patientName: "Sarah Davis",
      date: new Date(2025, 4, 7),
      time: "10:00 AM",
      duration: 60,
      status: "scheduled",
      notes: "Initial consultation",
    },
    {
      id: "apt-105",
      patientName: "Robert Wilson",
      date: new Date(2025, 4, 7),
      time: "1:00 PM",
      duration: 60,
      status: "scheduled",
      notes: "Discussing medication options",
    },
    {
      id: "apt-106",
      patientName: "Jennifer Lee",
      date: new Date(2025, 4, 8),
      time: "9:00 AM",
      duration: 60,
      status: "scheduled",
      notes: "Weekly check-in",
    },
    {
      id: "apt-107",
      patientName: "David Martinez",
      date: new Date(2025, 4, 8),
      time: "11:00 AM",
      duration: 60,
      status: "scheduled",
      notes: "Follow-up session",
    },
    {
      id: "apt-108",
      patientName: "Lisa Thompson",
      date: new Date(2025, 4, 8),
      time: "2:00 PM",
      duration: 60,
      status: "scheduled",
      notes: "Stress management techniques",
    },
    {
      id: "apt-109",
      patientName: "James Anderson",
      date: new Date(2025, 3, 30),
      time: "10:00 AM",
      duration: 60,
      status: "completed",
      notes: "Weekly session",
    },
    {
      id: "apt-110",
      patientName: "Patricia Garcia",
      date: new Date(2025, 3, 30),
      time: "1:00 PM",
      duration: 60,
      status: "missed",
      notes: "No-show",
    },
    {
      id: "apt-111",
      patientName: "Thomas Wright",
      date: new Date(2025, 3, 29),
      time: "3:00 PM",
      duration: 60,
      status: "cancelled",
      notes: "Cancelled by patient",
    },
  ]
  
  // Mock therapists
  export const mockTherapists = [
    {
      id: "th-001",
      name: "Dr. Sarah Johnson",
      specialty: "Cognitive Behavioral Therapy",
      bio: "Specializes in anxiety, depression, and stress management with 10+ years of experience.",
      image: "/placeholder.svg?height=80&width=80",
      tags: ["Anxiety", "Depression", "Stress", "CBT"],
      availability: "high",
    },
    {
      id: "th-002",
      name: "Dr. Michael Chen",
      specialty: "Family Therapy",
      bio: "Expert in family dynamics, relationship issues, and conflict resolution.",
      image: "/placeholder.svg?height=80&width=80",
      tags: ["Family", "Relationships", "Conflict Resolution"],
      availability: "medium",
    },
    {
      id: "th-003",
      name: "Dr. Robert Williams",
      specialty: "Psychotherapy",
      bio: "Focuses on trauma recovery, PTSD, and emotional regulation.",
      image: "/placeholder.svg?height=80&width=80",
      tags: ["Trauma", "PTSD", "Emotional Regulation"],
      availability: "low",
    },
    {
      id: "th-004",
      name: "Dr. Jennifer Lopez",
      specialty: "Child Psychology",
      bio: "Specializes in child development, behavioral issues, and parenting support.",
      image: "/placeholder.svg?height=80&width=80",
      tags: ["Children", "Behavior", "Parenting"],
      availability: "medium",
    },
  ]
  
  // Mock waiting list entries
  export const mockWaitingListEntries = [
    {
      id: "wl-001",
      patientName: "Emma Wilson",
      requestDate: "April 30, 2025",
      preferredDates: "May 10-15, 2025",
      preferredTimes: "Afternoons (2-5 PM)",
      expiryDate: "May 20, 2025",
      notes: "Looking for weekly sessions to address anxiety issues",
      status: "active",
      matchesAvailability: true,
      matchingSlot: "May 12, 2025 at 3:00 PM",
    },
    {
      id: "wl-002",
      patientName: "Daniel Brown",
      requestDate: "May 1, 2025",
      preferredDates: "May 7-12, 2025",
      preferredTimes: "Mornings (9 AM-12 PM)",
      expiryDate: "May 15, 2025",
      notes: "Need help with relationship counseling",
      status: "active",
      matchesAvailability: true,
      matchingSlot: "May 10, 2025 at 10:00 AM",
    },
    {
      id: "wl-003",
      patientName: "Sophia Martinez",
      requestDate: "April 28, 2025",
      preferredDates: "May 5-10, 2025",
      preferredTimes: "Evenings (5-8 PM)",
      expiryDate: "May 12, 2025",
      notes: "Seeking support for work-related stress",
      status: "active",
      matchesAvailability: false,
    },
    {
      id: "wl-004",
      patientName: "Oliver Johnson",
      requestDate: "April 25, 2025",
      preferredDates: "May 3-8, 2025",
      preferredTimes: "Afternoons (1-4 PM)",
      expiryDate: "May 9, 2025",
      notes: "Need help with depression management",
      status: "active",
      matchesAvailability: false,
    },
    {
      id: "wl-005",
      patientName: "Ava Thompson",
      requestDate: "April 20, 2025",
      preferredDates: "April 25-30, 2025",
      preferredTimes: "Mornings (9 AM-12 PM)",
      expiryDate: "May 4, 2025",
      notes: "Looking for family therapy sessions",
      status: "processed",
      resolution: "Appointment scheduled for April 28, 2025 at 10:00 AM",
      processedDate: "April 22, 2025",
    },
    {
      id: "wl-006",
      patientName: "Noah Garcia",
      requestDate: "April 18, 2025",
      preferredDates: "April 23-28, 2025",
      preferredTimes: "Evenings (5-8 PM)",
      expiryDate: "May 2, 2025",
      notes: "Need help with anxiety and panic attacks",
      status: "processed",
      resolution: "Patient found another therapist",
      processedDate: "April 25, 2025",
    },
  ]
  