# Generated by Django 4.2.7 on 2025-04-30 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("AI_engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialInteractionAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "engagement_score",
                    models.FloatField(
                        help_text="Score representing user's social engagement level"
                    ),
                ),
                (
                    "interaction_patterns",
                    models.JSONField(
                        default=dict, help_text="Patterns of user interactions"
                    ),
                ),
                (
                    "therapeutic_content",
                    models.JSONField(
                        default=list,
                        help_text="Content that has therapeutic value for user",
                    ),
                ),
                (
                    "support_network",
                    models.JSONField(
                        default=dict, help_text="Analysis of user's support network"
                    ),
                ),
                (
                    "content_preferences",
                    models.JSONField(
                        default=dict, help_text="Content types user engages with most"
                    ),
                ),
                (
                    "mood_correlation",
                    models.JSONField(
                        default=dict,
                        help_text="Correlation between social activity and mood",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-analysis_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-analysis_date"],
                        name="AI_engine_s_user_id_614b8d_idx",
                    ),
                    models.Index(
                        fields=["engagement_score"],
                        name="AI_engine_s_engagem_983306_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MedicationEffectAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "medications",
                    models.JSONField(
                        default=list, help_text="Current medications being analyzed"
                    ),
                ),
                (
                    "mood_effects",
                    models.JSONField(default=dict, help_text="Effects on mood"),
                ),
                (
                    "side_effects_detected",
                    models.JSONField(
                        default=list, help_text="Potential side effects detected"
                    ),
                ),
                (
                    "adherence_patterns",
                    models.JSONField(
                        default=dict, help_text="Medication adherence patterns"
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list,
                        help_text="AI recommendations regarding medication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-analysis_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-analysis_date"],
                        name="AI_engine_m_user_id_69d917_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ConversationSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conversation_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("start_message_id", models.CharField(max_length=255)),
                ("end_message_id", models.CharField(max_length=255)),
                ("message_count", models.IntegerField()),
                (
                    "summary_text",
                    models.TextField(
                        help_text="AI-generated summary of conversation segment"
                    ),
                ),
                (
                    "key_points",
                    models.JSONField(
                        default=list, help_text="Key points from the conversation"
                    ),
                ),
                (
                    "emotional_context",
                    models.JSONField(
                        default=dict, help_text="Emotional context of conversation"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["conversation_id", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation_id"],
                        name="AI_engine_c_convers_c364d0_idx",
                    ),
                    models.Index(
                        fields=["user", "conversation_id"],
                        name="AI_engine_c_user_id_e0dfc3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommunicationPatternAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "therapeutic_relationships",
                    models.JSONField(
                        default=dict,
                        help_text="Analysis of user's therapeutic relationships",
                    ),
                ),
                (
                    "conversation_metrics",
                    models.JSONField(
                        default=dict, help_text="Metrics about conversation patterns"
                    ),
                ),
                (
                    "communication_style",
                    models.JSONField(
                        default=dict,
                        help_text="User's communication style characteristics",
                    ),
                ),
                (
                    "response_patterns",
                    models.JSONField(
                        default=dict,
                        help_text="Patterns in how user responds to different approaches",
                    ),
                ),
                (
                    "emotional_triggers",
                    models.JSONField(
                        default=list,
                        help_text="Topics that trigger emotional responses",
                    ),
                ),
                (
                    "improvement_areas",
                    models.JSONField(
                        default=list,
                        help_text="Areas where communication could be improved",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-analysis_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-analysis_date"],
                        name="AI_engine_c_user_id_374966_idx",
                    )
                ],
            },
        ),
    ]
