# Generated by Django 4.2.7 on 2025-04-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmessage",
            name="media",
            field=models.FileField(
                blank=True,
                help_text="Upload media files (images, videos, PDFs, etc.)",
                null=True,
                upload_to="uploads/group/",
            ),
        ),
        migrations.AddField(
            model_name="onetoonemessage",
            name="media",
            field=models.FileField(
                blank=True,
                help_text="Upload media files (images, videos, PDFs, etc.)",
                null=True,
                upload_to="uploads/one_to_one/",
            ),
        ),
    ]
