# Generated by Django 4.2.7 on 2025-04-30 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0003_groupmessage_media_onetoonemessage_media"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatbotmessage",
            name="conversation",
        ),
        migrations.RemoveField(
            model_name="chatbotmessage",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="chatbotmessage",
            name="edited_by",
        ),
        migrations.RemoveField(
            model_name="chatbotmessage",
            name="read_by",
        ),
        migrations.RemoveField(
            model_name="chatbotmessage",
            name="sender",
        ),
        migrations.DeleteModel(
            name="ChatbotConversation",
        ),
        migrations.DeleteModel(
            name="ChatbotMessage",
        ),
    ]
